# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: V0alz space
tagline: My brain poops here.
email: v0alzgames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freshly baked home made games.
  Tutorials and brain poop.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: V0alz
github_username:  V0alz

# Build settings
markdown: kramdown
